/**
 * Portado de `frontend/app/src/app/shared/config/route-access-rules.config.ts`
 */
import { ACCESS_CONFIG } from './accessConfig';
import type { AccessRuleItem } from './appEnvironment.types';

export const ROUTE_ACCESS_RULES: Record<string, AccessRuleItem[] | null> = {
  HOME: null,

  REPORT_HISTORICO: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
    ACCESS_CONFIG.TRANSPORTADORA,
  ],

  RELATORIO: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
  ],

  PONTO_ATENDIMENTO: [ACCESS_CONFIG.MASTER, ACCESS_CONFIG.OPERADOR_LOGISTICO],

  REGISTER: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],

  INVITE: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],

  REGISTER_LIST: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],

  PERSON_LIST: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],

  VEHICLE_LIST: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],

  PERSON_CREATE: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],

  PERSON_EDIT: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],

  PERSON_IMPORT: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],

  VEHICLE_CREATE: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],

  VEHICLE_EDIT: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],

  VEHICLE_IMPORT: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],

  PONTO_ATENDIMENTO_LIST: [ACCESS_CONFIG.MASTER],
  PONTO_ATENDIMENTO_CREATE: [ACCESS_CONFIG.MASTER],
  PONTO_ATENDIMENTO_EDIT: [ACCESS_CONFIG.MASTER],
  INSTALACAO_NUC_LIST: [ACCESS_CONFIG.MASTER],
  INSTALACAO_NUC_CREATE: [ACCESS_CONFIG.MASTER],
  INSTALACAO_NUC_EDIT: [ACCESS_CONFIG.MASTER],
  TRANSPORTADORA_LIST: [ACCESS_CONFIG.OPERADOR_LOGISTICO],
  TRANSPORTADORA_EDIT: [ACCESS_CONFIG.OPERADOR_LOGISTICO],
  TRANSPORTADORA_TIPO_ENVIO_LIST: [ACCESS_CONFIG.OPERADOR_LOGISTICO],
  TRANSPORTADORA_TIPO_ENVIO_EDIT: [ACCESS_CONFIG.OPERADOR_LOGISTICO],

  INVITE_LIST: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],
  INVITE_GUESTS: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],

  WHATSAPP_CONFIG: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
  ],

  ENVIAR_CONVITE: [
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],
  ENVIAR_CONVITE_LIST: [
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],
  ENVIAR_CONVITE_IMPORT: [
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],

  GERENCIAR_CONVITES: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],
  GERENCIAR_CONVITES_LIST: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],
  GERENCIAR_CONVITES_CONVIDADOS: [
    ACCESS_CONFIG.MASTER,
    ACCESS_CONFIG.TRANSPORTADORA,
    ACCESS_CONFIG.EMBARCADOR,
    ACCESS_CONFIG.OPERADOR_LOGISTICO,
  ],

  ENVIO_CONFIG: [ACCESS_CONFIG.MASTER],
};

export type RouteAccessRuleKey = keyof typeof ROUTE_ACCESS_RULES;
